spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/harmonia
    username: postgres
    password: harmonia
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  profiles:
    active: local

logging:
  level:
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized

harmonia:
  user: admin
  password: admin1234
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://localhost:5174"
      - "http://localhost:5175"
      - "http://localhost:3000"
      - "http://localhost:8080"
  ai:
    enabled: true
    commit-classifier:
      enabled: true
      confidence-threshold: 0.7
    anomaly-detector:
      enabled: true
      confidence-threshold: 0.7
    file-clustering:
      enabled: false
  attendance:
    start-row-index: 4
    row-step: 3
    team-name-column: 0
    student1-columns: [ 4, 8, 12 ]
    student2-columns: [ 5, 9, 13 ]
    number-programming-sessions: 3
    mandatory-programming-sessions: 2
  projects:
    - id: itp-2526
      courseName: ITP
      semester: WS 25/26
      exerciseId: 18806
      gitRepoPath: Projects/itp2526teamprojects
    - id: itp-2425
      courseName: ITP
      semester: WS 24/25
      exerciseId: 15535
      gitRepoPath: Projects/itp2425teamprojects
    

artemis:
  baseUrl: https://artemis.cit.tum.de
  username: 
  password: 
  jwtToken: 
  numThreads: 8
