spring:
  ai:
    azure:
      openai:
        enabled: false
        endpoint: http://disabled
        api-key: disabled
    openai:
      enabled: false
      api-key: "disabled"
      base-url: "http://disabled"

  datasource:
    url: jdbc:h2:mem:openapi;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop

  security:
    user:
      name: disabled
      password: disabled

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  default-produces-media-type: application/json