spring:
  ai:
    azure:
      openai:
        enabled: false
        endpoint: http://disabled
        api-key: disabled
    openai:
      enabled: false
      api-key: "disabled"
      base-url: "http://disabled"

  liquibase:
    enabled: false

  security:
    user:
      name: disabled
      password: disabled

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  default-produces-media-type: application/json